version: '3.8'
services:
  pgdatabase:
    image: postgres:16
    container_name: postgres_a3
    environment:
      - POSTGRES_USER=dashaqui
      - POSTGRES_PASSWORD=dashaqui
      - POSTGRES_DB=lakehouse_a3
    volumes:
      - "../data/postgres:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - lakehouse_a3
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_a3
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "../data/pg_admin:/var/lib/pgadmin:rw"
    ports:
      - "8070:80"
    networks:
      - lakehouse_a3
    
networks:
  lakehouse_a3:
    driver: bridge